### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by hoshino1212** [hoshino1212/portfolio#20]
- [ ] ユーザー登録フォームを実装する
- [ ] ログインフォームを実装する
- [ ] Sorceryによるユーザー認証を実装する
- [ ] パスワード変更フォームを実装する
- [ ] パスワード変更処理を実装する
- [ ] メールアドレス変更フォームを実装する
- [ ] メールアドレス変更処理を実装する
- [ ] 禁煙開始日、1日あたりの喫煙本数、一箱の価格を入力するフォームを実装する
- [ ] リマインダー時間を設定するフォームを実装する
- [ ] リマインダー時間に基づいてメールを送信する処理を実装する
- [ ] リマインダー通知用のメールテンプレートを作成する
- [ ] ユーザー登録とログインを表示する

**Comment by kenchasonakai** [comment]
> また、作成したGitHubProjectをpublicに変更して、URLの共有もお願いします。

カリキュラムに上記項目あるかと思いますのでご確認お願いします

**Comment by hoshino1212** [comment]
確認不足でした。
お手数をお掛けして申し訳ありません。

**Comment by kenchasonakai** [comment]
LGTMです！
